- hosts: datanodes
  gather_facts: no
  tasks: 

  - file:
        path: "/share"
        state: directory

  - name: config hdfs file
    blockinfile:
        path: "/etc/hadoop/hdfs-site.xml"
        state: present
        insertafter: "<configuration>"
        block: |
          <property>
          <name>dfs.name.dir</name>
          <value>/share</value>
          </property>

  - name: config core file
    blockinfile:
        path: "/etc/hadoop/core-site.xml"
        state: present
        insertafter: "<configuration>"
        block: |
          <property>
          <name>fs.default.name</name>
          <value>hdfs://192.168.43.167:9001</value>
          </property>
  - name: start data node
    command: "hadoop-daemon.sh start datanode"
    ignore_errors: yes
